// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReactiveMemory.GeneratorCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DataBaseContextTemplate : DataBaseContextTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// <auto-generated />\r\n#pragma warning disable CS0105\r\n");
            
            #line 8 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Using));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nnamespace ");
            
            #line 10 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n   public sealed class ");
            
            #line 12 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("  : IDisposable\r\n   {\r\n        public bool IsTransactionStarted { get; private set; }\r\n        public event Action OnUnauthorizedMemoryModification;\r\n\t\tpublic I");
            
            #line 16 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemoryDatabaseClassName));
            
            #line default
            #line hidden
            this.Write("  Database => _database ??= new ");
            
            #line 16 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemoryDatabaseClassName));
            
            #line default
            #line hidden
            this.Write("(_data, _changesConveyor);\r\n        public I");
            
            #line 17 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TransactionClassName));
            
            #line default
            #line hidden
            this.Write("  Transaction => _transaction;\r\n\r\n        private ");
            
            #line 19 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemoryDatabaseClassName));
            
            #line default
            #line hidden
            this.Write(" _database;\r\n        private ");
            
            #line 20 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TransactionClassName));
            
            #line default
            #line hidden
            this.Write(" _transaction;\r\n        private ChangesConveyor _changesConveyor;\r\n        private byte[] _data;\r\n        private byte[] _hash;\r\n        private MD5 _md5;\r\n\r\n        public DbContext(byte[] dbBytes, IChangesMediatorFactory changesMediatorFactory, string md5 = \"\")\r\n        {\r\n            _changesConveyor = new ChangesConveyor(changesMediatorFactory);\r\n            _data = dbBytes;\r\n            if(!string.IsNullOrWhiteSpace(md5))\r\n\t\t\t{\r\n\t\t\t\t_md5 = MD5.Create(md5);\r\n\t\t\t\t_hash = _md5.ComputeHash(_data);\r\n\t\t\t}\r\n        }\r\n\r\n        public I");
            
            #line 37 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TransactionClassName));
            
            #line default
            #line hidden
            this.Write(" BeginTransaction()\r\n        {\r\n            if (IsTransactionStarted)\r\n            {\r\n                throw new InvalidOperationException(\"Transaction is already started\");\r\n            }\r\n\r\n            IsTransactionStarted = true;\r\n            if (_database == null)\r\n            {\r\n                // serialization of db from bytes, it's slow\r\n                _database = new ");
            
            #line 48 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemoryDatabaseClassName));
            
            #line default
            #line hidden
            this.Write("(_data, _changesConveyor);\r\n            }\r\n            else if(_md5 != null)\r\n            {\r\n                // calc hash of current db data\r\n                var prevDataHash = _md5.ComputeHash(_data); \r\n                if (!prevDataHash.SequenceEqual(_hash) || !prevDataHash.SequenceEqual(_md5.ComputeHash(ToBytes())))\r\n                {\r\n                    // detected memory modifications\r\n                    OnUnauthorizedMemoryModification?.Invoke();\r\n                }\r\n            }\r\n            // it just cast, but when we make changes it make copy of data, so Database will not be changed\r\n            _transaction = _database.BeginTransaction();\r\n            return _transaction;\r\n        }\r\n\r\n\r\n        public void Commit()\r\n        {\r\n            if (!IsTransactionStarted)\r\n            {\r\n                throw new InvalidOperationException(\"Transaction is not started\");\r\n            }\r\n\r\n            // cast to  ");
            
            #line 73 "E:\Repositories\ReactiveMemory\src\ReactiveMemory.GeneratorCore\DataBaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MemoryDatabaseClassName));
            
            #line default
            #line hidden
            this.Write(" \r\n            _database = _transaction.Commit();\r\n            if(_md5 != null)\r\n\t\t\t{\r\n\t\t\t\t_data = ToBytes();\r\n\t\t\t\t_hash = _md5.ComputeHash(_data);\r\n\t\t\t}\r\n            IsTransactionStarted = false;\r\n        }\r\n\r\n        public void Rollback()\r\n        {\r\n            // all changes in Transaction, so we just set it to null to discard changes\r\n            _database.ChangesConveyor.Clear();\r\n            _transaction = null;\r\n            IsTransactionStarted = false;\r\n        }\r\n        \r\n        public byte[] ToBytes()\r\n        {\r\n            return _database.ToDatabaseBuilder().Build();\r\n        }\r\n\r\n        public void Dispose()\r\n        {\r\n            _changesConveyor?.Dispose();\r\n            _md5?.Dispose();\r\n        }\r\n   }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DataBaseContextTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
